version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    links:
      - mysql
    working_dir: /var/www/html

  nginx:
    build:
      context: .
      dockerfile: NGINX-DOCKERFILE
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
  


  mysql:
    image: mysql:8.0
    user: mysql
    volumes:
      - ./docker/.data/db:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    command: ["--default-authentication-plugin=mysql_native_password"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    links:
      - mysql
      - php